CREATE TABLE `apartment_complexes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`zip` varchar(20) NOT NULL,
	`neighborhood` varchar(100),
	`latitude` float,
	`longitude` float,
	`totalUnits` int NOT NULL DEFAULT 1,
	`yearBuilt` int,
	`stories` int,
	`hasPool` tinyint DEFAULT 0,
	`hasGym` tinyint DEFAULT 0,
	`hasElevator` tinyint DEFAULT 0,
	`hasDoorman` tinyint DEFAULT 0,
	`hasParking` tinyint DEFAULT 0,
	`hasLaundry` tinyint DEFAULT 0,
	`petPolicy` enum('allowed','not_allowed','case_by_case') DEFAULT 'case_by_case',
	`photos` text,
	`coverPhotoUrl` text,
	`contactName` varchar(255),
	`contactEmail` varchar(320),
	`contactPhone` varchar(30),
	`website` varchar(500),
	`status` enum('active','inactive') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `apartment_complexes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `complex_units` (
	`id` int AUTO_INCREMENT NOT NULL,
	`complexId` int NOT NULL,
	`userId` int NOT NULL,
	`unitNumber` varchar(20) NOT NULL,
	`floor` int,
	`monthlyRent` int NOT NULL,
	`securityDeposit` int,
	`bedrooms` varchar(10) NOT NULL,
	`bathrooms` varchar(10) NOT NULL,
	`squareFeet` int,
	`availableDate` varchar(30),
	`petFriendly` tinyint DEFAULT 0,
	`washerDryer` tinyint DEFAULT 0,
	`airConditioning` tinyint DEFAULT 0,
	`dishwasher` tinyint DEFAULT 0,
	`balcony` tinyint DEFAULT 0,
	`utilities` enum('included','not_included','partial') DEFAULT 'not_included',
	`photos` text,
	`description` text,
	`status` enum('available','occupied','reserved','maintenance') NOT NULL DEFAULT 'available',
	`marketplaceListingId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `complex_units_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `istay_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listingId` int NOT NULL,
	`hostUserId` int NOT NULL,
	`guestUserId` int,
	`guestName` varchar(255) NOT NULL,
	`guestEmail` varchar(320) NOT NULL,
	`guestPhone` varchar(30),
	`guestCount` int NOT NULL DEFAULT 1,
	`checkIn` varchar(20) NOT NULL,
	`checkOut` varchar(20) NOT NULL,
	`nights` int NOT NULL,
	`pricePerNight` int NOT NULL,
	`subtotal` int NOT NULL,
	`cleaningFee` int DEFAULT 0,
	`serviceFee` int DEFAULT 0,
	`totalAmount` int NOT NULL,
	`stripePaymentIntentId` varchar(255),
	`stripeCheckoutSessionId` varchar(255),
	`paymentStatus` enum('pending','paid','failed','refunded') DEFAULT 'pending',
	`paidAt` timestamp,
	`status` enum('pending','confirmed','cancelled_by_guest','cancelled_by_host','completed','no_show') NOT NULL DEFAULT 'pending',
	`specialRequests` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `istay_bookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `istay_listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`propertyType` enum('entire_home','private_room','shared_room','hotel_room','apartment','condo','villa','cabin','cottage','loft','studio','penthouse','townhouse','other') NOT NULL DEFAULT 'entire_home',
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`zip` varchar(20) NOT NULL,
	`country` varchar(100) DEFAULT 'United States',
	`neighborhood` varchar(100),
	`latitude` float,
	`longitude` float,
	`pricePerNight` int NOT NULL,
	`cleaningFee` int DEFAULT 0,
	`serviceFee` int DEFAULT 0,
	`weeklyDiscount` int DEFAULT 0,
	`monthlyDiscount` int DEFAULT 0,
	`maxGuests` int NOT NULL DEFAULT 1,
	`bedrooms` int NOT NULL DEFAULT 1,
	`beds` int NOT NULL DEFAULT 1,
	`bathrooms` varchar(10) DEFAULT '1',
	`minNights` int NOT NULL DEFAULT 1,
	`maxNights` int DEFAULT 365,
	`checkInTime` varchar(10) DEFAULT '15:00',
	`checkOutTime` varchar(10) DEFAULT '11:00',
	`amenities` text,
	`smokingAllowed` tinyint DEFAULT 0,
	`petsAllowed` tinyint DEFAULT 0,
	`partiesAllowed` tinyint DEFAULT 0,
	`childrenAllowed` tinyint DEFAULT 1,
	`houseRules` text,
	`photos` text,
	`coverPhotoUrl` text,
	`hostName` varchar(255),
	`hostPhotoUrl` text,
	`hostBio` text,
	`isSuperhost` tinyint DEFAULT 0,
	`averageRating` float,
	`reviewCount` int DEFAULT 0,
	`cancellationPolicy` enum('flexible','moderate','strict','super_strict') DEFAULT 'moderate',
	`status` enum('active','inactive','pending_review') NOT NULL DEFAULT 'active',
	`instantBook` tinyint DEFAULT 1,
	`viewCount` int NOT NULL DEFAULT 0,
	`saveCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `istay_listings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `istay_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listingId` int NOT NULL,
	`bookingId` int NOT NULL,
	`reviewerUserId` int,
	`reviewerName` varchar(255) NOT NULL,
	`overallRating` int NOT NULL,
	`cleanlinessRating` int,
	`accuracyRating` int,
	`communicationRating` int,
	`locationRating` int,
	`valueRating` int,
	`comment` text,
	`hostResponse` text,
	`hostRespondedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `istay_reviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `istay_saves` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listingId` int NOT NULL,
	`userId` int NOT NULL,
	`savedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `istay_saves_id` PRIMARY KEY(`id`)
);
