CREATE TABLE `area_rent_rates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`zipCode` varchar(10),
	`propertyType` enum('studio','1br','2br','3br','4br_plus','room','co_living') NOT NULL,
	`medianRent` int NOT NULL,
	`minRent` int,
	`maxRent` int,
	`sampleSize` int DEFAULT 0,
	`dataSource` varchar(100) DEFAULT 'leasely_platform',
	`lastUpdated` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `area_rent_rates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `custom_application_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`fileUrl` text,
	`fileKey` varchar(500),
	`isDefault` tinyint DEFAULT 0,
	`templateType` enum('leasely_builtin','custom_upload') NOT NULL DEFAULT 'leasely_builtin',
	`state` varchar(2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `custom_application_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rental_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listingId` int NOT NULL,
	`landlordUserId` int NOT NULL,
	`applicantName` varchar(255) NOT NULL,
	`applicantEmail` varchar(320) NOT NULL,
	`applicantPhone` varchar(30),
	`applicantDob` varchar(20),
	`currentAddress` text,
	`currentLandlordName` varchar(255),
	`currentLandlordPhone` varchar(30),
	`currentRent` varchar(20),
	`reasonForLeaving` text,
	`employerName` varchar(255),
	`employerPhone` varchar(30),
	`occupation` varchar(255),
	`monthlyIncome` varchar(30),
	`applicationFormType` enum('standard','coliving_member') NOT NULL DEFAULT 'standard',
	`moveInDate` varchar(20),
	`roomPreference` varchar(100),
	`lifestyleNotes` text,
	`state` varchar(2),
	`stateDisclosureAgreed` tinyint DEFAULT 0,
	`hasPets` tinyint DEFAULT 0,
	`petDescription` text,
	`vehicleInfo` text,
	`emergencyContactName` varchar(255),
	`emergencyContactPhone` varchar(30),
	`emergencyContactRelation` varchar(100),
	`additionalOccupants` text,
	`backgroundCheckConsent` tinyint DEFAULT 0,
	`creditCheckConsent` tinyint DEFAULT 0,
	`signatureDataUrl` text,
	`signedAt` timestamp,
	`status` enum('submitted','reviewing','approved','denied','withdrawn') NOT NULL DEFAULT 'submitted',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rental_applications_id` PRIMARY KEY(`id`)
);
