// Seed data for the state-specific lease templates.
//
// These are the *source-of-truth* template bodies. On server startup, the DB
// is checked for each (state, category) pair; if missing, the row is inserted
// here. Admin edits in the lease_template_versions table take precedence —
// the seed only runs when there is no active version yet.
//
// To add a new state without changing core code: append a new SeedTemplate
// entry here with its state code, category, body (with {{placeholders}}),
// citations, and disclosures. Run the server once and it appears in the UI.

export interface SeedTemplate {
  state: string;                                                      // "NC", "TN", "ALL"
  category: "standard_residential" | "coliving_room_rental" | "generic";
  name: string;
  description: string;
  bodyHtml: string;
  variables: string[];
  citations: string[];
  disclosures: string[];
}

const COMPLIANCE_BLOCK = `
<section class="legal-disclaimer">
  <p><strong>Legal Disclaimer.</strong> This lease was generated by Leasely from a state-specific template. Leasely is not a law firm and does not provide legal advice. The Landlord and Tenant should each consult an attorney licensed in {{state}} before signing if either has questions about their rights and obligations. Statutory citations are provided for reference only.</p>
</section>`;

const FEDERAL_LEAD_PAINT = `
<section>
  <h2>Federal Lead-Based Paint Disclosure</h2>
  <p>Housing built before 1978 may contain lead-based paint. If the Property was built before 1978, Landlord shall provide Tenant with the EPA pamphlet <em>"Protect Your Family From Lead in Your Home"</em> and any known information concerning lead-based paint or lead-based paint hazards, in compliance with 42 U.S.C. § 4852d and 24 CFR § 35.92.</p>
</section>`;

const SIGNATURE_BLOCK = `
<section>
  <h2>Signatures</h2>
  <div class="signature-block">
    <p><strong>Landlord:</strong> ____________________________ &nbsp; Date: ____________</p>
    <p><strong>Tenant:</strong> ____________________________ &nbsp; Date: ____________</p>
  </div>
</section>`;

// ─── Early Termination (Lease Break) ──────────────────────────────────────────
// State-specific buyout language. Two universal principles apply in every U.S.
// state: (1) the landlord has a duty to mitigate damages by making reasonable
// efforts to re-let, and (2) servicemembers may terminate under the SCRA
// (50 U.S.C. § 3955) with 30 days' notice + a copy of orders. State-specific
// statutory protections (domestic violence, habitability) are added per state.
const EARLY_TERMINATION_NC = `
<section>
  <h2>Early Termination by Tenant (Lease Break)</h2>
  <p><strong>Notice and fee.</strong> If Tenant wishes to end this Lease before the Lease End Date for any reason not protected by statute, Tenant shall (a) provide Landlord with at least <strong>sixty (60) days' written notice</strong> of the intended vacate date, and (b) pay an <strong>early-termination fee equal to two (2) months' rent</strong>, OR the rent that would be owed for the remainder of the term, <em>whichever is less</em>. The fee is in addition to any unpaid rent, damages beyond ordinary wear and tear, and lawful deductions from the security deposit under <em>N.C. Gen. Stat. § 42-51 and § 42-52</em>.</p>
  <p><strong>Landlord's duty to mitigate.</strong> If Tenant vacates before the term ends, Landlord shall make reasonable efforts to re-let the Property at a comparable rent. Tenant remains liable for rent only until the Property is re-let to a replacement tenant or the original Lease End Date, whichever comes first, less Landlord's reasonable re-letting costs (advertising, showings, screening, broker fees if any). North Carolina recognizes a landlord's mitigation duty in residential leases; this clause restates that duty for clarity.</p>
  <p><strong>Statutorily protected terminations.</strong> Tenant may terminate without paying the early-termination fee in the following situations, each of which has its own notice and documentation requirements:</p>
  <ul>
    <li><strong>Active military service (SCRA).</strong> Under the federal Servicemembers Civil Relief Act, <em>50 U.S.C. § 3955</em>, a servicemember who enters active duty or receives PCS / deployment orders of 90+ days may terminate by giving Landlord written notice with a copy of orders; the Lease terminates 30 days after the next rent due date.</li>
    <li><strong>Domestic violence, sexual assault, or stalking.</strong> Pursuant to <em>N.C. Gen. Stat. § 42-45.1</em>, a victim with a valid protective order, criminal restraining order, or qualifying court order or law-enforcement documentation may terminate the Lease by giving Landlord 30 days' written notice. Tenant is liable only for rent through the termination date.</li>
    <li><strong>Uninhabitable premises.</strong> If Landlord fails to comply with the duties imposed by <em>N.C. Gen. Stat. § 42-42</em> after written notice and a reasonable opportunity to cure, Tenant may pursue the remedies available under § 42-44, which may include termination in certain circumstances.</li>
  </ul>
  <p><strong>Security deposit.</strong> The security deposit may be applied to unpaid rent, the early-termination fee, and damages beyond ordinary wear and tear, in accordance with <em>N.C. Gen. Stat. § 42-51</em>. Any balance shall be returned within 30 days (or 60 days if a final accounting is required) per <em>§ 42-52</em>.</p>
</section>`;

const EARLY_TERMINATION_TN = `
<section>
  <h2>Early Termination by Tenant (Lease Break)</h2>
  <p><strong>Notice and fee.</strong> If Tenant wishes to end this Lease before the Lease End Date for any reason not protected by statute, Tenant shall (a) provide Landlord with at least <strong>sixty (60) days' written notice</strong> of the intended vacate date, and (b) pay an <strong>early-termination fee equal to two (2) months' rent</strong>, OR the rent that would be owed for the remainder of the term, <em>whichever is less</em>. The fee is in addition to any unpaid rent, damages beyond ordinary wear and tear, and lawful deductions from the security deposit under <em>Tenn. Code Ann. § 66-28-301 and § 66-28-305</em>.</p>
  <p><strong>Landlord's duty to mitigate.</strong> If Tenant vacates before the term ends, Landlord shall make reasonable efforts to re-let the Property at a comparable rent. In URLTA counties, this duty is codified at <em>Tenn. Code Ann. § 66-28-507</em>. Tenant remains liable for rent only until the Property is re-let or the original Lease End Date, whichever comes first, less Landlord's reasonable re-letting costs.</p>
  <p><strong>Statutorily protected terminations.</strong> Tenant may terminate without paying the early-termination fee in the following situations, each of which has its own notice and documentation requirements:</p>
  <ul>
    <li><strong>Active military service (SCRA).</strong> Under <em>50 U.S.C. § 3955</em>, a servicemember entering active duty or receiving PCS / deployment orders of 90+ days may terminate by giving Landlord written notice with a copy of orders; the Lease terminates 30 days after the next rent due date.</li>
    <li><strong>Domestic violence, sexual assault, or stalking.</strong> Pursuant to <em>Tenn. Code Ann. § 66-7-109</em>, a victim with a qualifying protective order or other documentation specified by statute may terminate the Lease by giving Landlord at least 30 days' written notice. Tenant is liable only for rent and damages accruing through the termination date.</li>
    <li><strong>Uninhabitable premises (URLTA counties).</strong> If Landlord fails to comply with <em>Tenn. Code Ann. § 66-28-304</em> after the 14-day cure notice required by <em>§ 66-28-501</em>, Tenant may terminate without further obligation. In non-URLTA counties this remedy is contractual rather than statutory but Landlord agrees to honor it.</li>
  </ul>
  <p><strong>Security deposit.</strong> The security deposit may be applied to unpaid rent, the early-termination fee, and damages beyond ordinary wear and tear, in accordance with <em>Tenn. Code Ann. § 66-28-301(g)</em>. Final accounting and any balance shall be provided within 30 days of the termination date.</p>
</section>`;

const EARLY_TERMINATION_GENERIC = `
<section>
  <h2>Early Termination by Tenant (Lease Break)</h2>
  <p><strong>Notice and fee.</strong> If Tenant wishes to end this Lease before the Lease End Date for any reason not protected by statute, Tenant shall (a) provide Landlord with at least <strong>sixty (60) days' written notice</strong> of the intended vacate date, and (b) pay an <strong>early-termination fee equal to two (2) months' rent</strong>, OR the rent that would be owed for the remainder of the term, <em>whichever is less</em>. The fee is in addition to any unpaid rent, damages beyond ordinary wear and tear, and lawful deductions from the security deposit.</p>
  <p><strong>Landlord's duty to mitigate.</strong> Nearly every U.S. state — by statute or by case law — requires Landlord to make reasonable efforts to re-let the Property after Tenant vacates. Tenant remains liable for rent only until the Property is re-let to a replacement tenant or the original Lease End Date, whichever comes first, less Landlord's reasonable re-letting costs.</p>
  <p><strong>Statutorily protected terminations.</strong> Tenant may terminate without paying the early-termination fee in the following situations (each with its own notice and documentation requirements under {{state}} law):</p>
  <ul>
    <li><strong>Active military service (SCRA).</strong> Under <em>50 U.S.C. § 3955</em>, a servicemember entering active duty or receiving PCS / deployment orders of 90+ days may terminate by giving Landlord written notice with a copy of orders.</li>
    <li><strong>Domestic violence, sexual assault, or stalking.</strong> Most states permit a victim with a qualifying protective order or court documentation to terminate on 30 days' written notice. The exact statute and documentation required vary by state — Tenant should consult {{state}} law.</li>
    <li><strong>Uninhabitable premises.</strong> If Landlord materially fails to maintain the Property in habitable condition after written notice and a reasonable opportunity to cure, Tenant may have a statutory or common-law right to terminate.</li>
  </ul>
  <p><strong>Security deposit.</strong> The security deposit may be applied to unpaid rent, the early-termination fee, and damages beyond ordinary wear and tear, in accordance with applicable {{state}} law. Final accounting timing varies by state (commonly 14 to 30 days).</p>
</section>`;

const NC_RESIDENTIAL: SeedTemplate = {
  state: "NC",
  category: "standard_residential",
  name: "North Carolina Residential Lease",
  description: "Standard residential lease grounded in N.C. Gen. Stat. Chapter 42.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "payment_methods",
  ],
  citations: [
    "N.C. Gen. Stat. § 42-3", "N.C. Gen. Stat. § 42-14", "N.C. Gen. Stat. § 42-25.6",
    "N.C. Gen. Stat. § 42-26", "N.C. Gen. Stat. § 42-42", "N.C. Gen. Stat. § 42-43",
    "N.C. Gen. Stat. § 42-46", "N.C. Gen. Stat. § 42-46(e)", "N.C. Gen. Stat. § 42-46(f)",
    "N.C. Gen. Stat. § 42-46(g)", "N.C. Gen. Stat. § 42-46(i)(3)", "N.C. Gen. Stat. § 42-46(i)(5)",
    "N.C. Gen. Stat. § 42-50", "N.C. Gen. Stat. § 42-51", "N.C. Gen. Stat. § 42-52",
    "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="NC" data-tenancy="residential">
  <header>
    <h1>North Carolina Residential Lease Agreement</h1>
    <p class="lease-subtitle">Governed by N.C. Gen. Stat. Chapter 42</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Property</h2>
    <p>Landlord leases to Tenant the residential premises located at <strong>{{property_address}}</strong> (the "Property"). Authorized occupants: {{occupants}}.</p>
  </section>

  <section><h2>3. Term</h2>
    <p>This Lease begins on <strong>{{lease_start_date}}</strong> and ends on <strong>{{lease_end_date}}</strong>. Either party may terminate a month-to-month tenancy by giving written notice at least <strong>seven (7) days</strong> before the end of the rental period, in accordance with <em>N.C. Gen. Stat. § 42-14</em>.</p>
  </section>

  <section><h2>4. Rent</h2>
    <p>Tenant shall pay rent of <strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong> of each month.</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
    <p><strong>Late fee.</strong> If any rental payment is five (5) or more calendar days late, Landlord may charge a late fee of <strong>{{late_fee}}</strong>, not to exceed the greater of $15.00 or 5% of the monthly rent under <em>N.C. Gen. Stat. § 42-46(a)</em>.</p>
  </section>

  <section><h2>5. Security Deposit</h2>
    <p>Tenant shall deposit <strong>{{security_deposit}}</strong>. Pursuant to <em>N.C. Gen. Stat. § 42-50</em>, the deposit may not exceed 1.5 months' rent for terms longer than month-to-month, one month's rent for month-to-month, or one week's rent for weekly tenancies.</p>
    <p>Pursuant to <em>§ 42-51</em>, the deposit shall be held in a trust account with a licensed and federally insured depository institution located in North Carolina, or secured by a bond. Landlord shall furnish Tenant with written notice of the name and address of the institution holding the deposit within <strong>thirty (30) days</strong> of the beginning of the lease term.</p>
    <p>Within <strong>thirty (30) days</strong> after termination of the tenancy (or <strong>sixty (60) days</strong> if a final accounting requires additional time), Landlord shall provide Tenant with an itemized accounting of any deductions and return the balance, in accordance with <em>§ 42-52</em>.</p>
  </section>

  <section><h2>6. Utilities</h2>
    <p>Utilities included: {{utilities}}. Utilities not listed are the responsibility of Tenant.</p>
  </section>

  <section><h2>7. Pets and Pet Fee</h2>
    <p>Pets allowed: {{pets_allowed}}. Any pet fee charged is non-refundable and is in addition to (not part of) the security deposit.</p>
  </section>

  <section><h2>8. Parking</h2>
    <p>{{parking}}</p>
  </section>

  <section><h2>9. Landlord Duties</h2>
    <p>Landlord shall comply with the duties imposed by <em>N.C. Gen. Stat. § 42-42</em>, including keeping the Property fit and habitable, complying with building and housing codes, making necessary repairs, and maintaining electrical, plumbing, sanitary, heating, ventilating, and air-conditioning facilities in good and safe working order.</p>
  </section>

  <section><h2>10. Tenant Duties</h2>
    <p>Tenant shall comply with <em>N.C. Gen. Stat. § 42-43</em>, including keeping the Property clean and safe, disposing of garbage properly, not damaging the Property, and not disturbing neighbors.</p>
  </section>

  <section><h2>11. Default, Cure, and Eviction</h2>
    <p><strong>Nonpayment of rent.</strong> If Tenant fails to pay rent when due and remains in default after lawful demand, Landlord may seek summary ejectment under <em>N.C. Gen. Stat. § 42-3</em> and <em>§ 42-26(a)(1)</em>. Eviction in North Carolina is by judicial process under § 42-25.6 et seq.; Landlord shall not use self-help (lockout, utility shutoff, or removal of property) under any circumstances.</p>
    <p><strong>Material breach.</strong> If Tenant materially breaches any other term of this Lease, Landlord shall give Tenant <strong>ten (10) days' written notice</strong> to cure (a contractual courtesy beyond what § 42-26 statutorily requires) before initiating summary ejectment under <em>§ 42-26(a)(2)</em>.</p>
    <p>Nothing in this Lease waives any non-waivable right of Tenant under North Carolina law.</p>
  </section>

  <section><h2>12. Fees Recoverable Under N.C. Gen. Stat. § 42-46</h2>
    <ul>
      <li><strong>Complaint-filing fee.</strong> If Landlord files a complaint for summary ejectment, Landlord may collect a complaint-filing fee not to exceed the greater of $15 or 5% of the monthly rent under <em>§ 42-46(e)</em>. This fee shall be refunded if the complaint is dismissed because Tenant cures the default.</li>
      <li><strong>Court-appearance fee.</strong> If Landlord prevails in small claims court, Landlord may collect a court-appearance fee not to exceed 10% of the monthly rent under <em>§ 42-46(f)</em>.</li>
      <li><strong>Second-trial fee.</strong> If Landlord prevails on appeal from a magistrate's judgment, Landlord may collect a second-trial fee not to exceed 12% of the monthly rent under <em>§ 42-46(g)</em>.</li>
      <li><strong>Reasonable attorney's fees.</strong> Pursuant to <em>§ 42-46(i)(3)</em>, Landlord may recover reasonable attorney's fees actually paid or owed, not to exceed 15% of the amount owed by Tenant, or 15% of the monthly rent if the eviction is based on a default other than nonpayment of rent.</li>
      <li><strong>Frivolous-appeal attorney's fees.</strong> If Tenant appeals a summary ejectment to district court and the court finds the appeal frivolous, unreasonable, without foundation, in bad faith, or solely for delay, Landlord may recover all actual reasonable attorney's fees under <em>§ 42-46(i)(5)</em>.</li>
    </ul>
  </section>

  ${EARLY_TERMINATION_NC}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const NC_COLIVING: SeedTemplate = {
  state: "NC",
  category: "coliving_room_rental",
  name: "North Carolina Co-Living / Room Rental Agreement",
  description: "Room-rental / membership agreement for co-living operators in North Carolina. Does NOT bypass eviction law.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "co_living_rules", "unit_or_room_label", "payment_methods",
  ],
  citations: [
    "N.C. Gen. Stat. § 42-14", "N.C. Gen. Stat. § 42-25.6", "N.C. Gen. Stat. § 42-26",
    "N.C. Gen. Stat. § 42-46", "N.C. Gen. Stat. § 42-50", "N.C. Gen. Stat. § 42-51",
    "N.C. Gen. Stat. § 42-52", "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="NC" data-tenancy="coliving_room_rental">
  <header>
    <h1>North Carolina Co-Living / Room Rental Agreement</h1>
    <p class="lease-subtitle">Room rental within a shared residence — eviction procedure under N.C. Gen. Stat. § 42 still applies</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Operator/Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Member/Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Nature of This Agreement</h2>
    <p>Tenant is granted the right to occupy <strong>{{unit_or_room_label}}</strong> at <strong>{{property_address}}</strong> (the "Residence") and to use the shared common areas. Operator reserves the right to enter the room with 24 hours' notice (except in emergencies) and may reassign Tenant to a comparable room within the Residence on 30 days' written notice.</p>
    <p>The "membership" or "room rental" framing applies to house rules and room assignment only. <strong>If Operator seeks to remove Tenant from possession, Operator will follow the applicable North Carolina eviction procedure (summary ejectment under N.C. Gen. Stat. § 42-25.6 et seq.) and will not engage in any self-help removal.</strong> Nothing in this Agreement waives any procedural protection or non-waivable right under North Carolina law.</p>
  </section>

  <section><h2>3. Monthly Fee</h2>
    <p>Tenant shall pay <strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong> of each month. The fee covers the right to occupy {{unit_or_room_label}}, use of common areas, and shared utilities ({{utilities}}).</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
    <p>Late fee: <strong>{{late_fee}}</strong>, not to exceed the greater of $15 or 5% of the monthly fee per <em>N.C. Gen. Stat. § 42-46(a)</em>.</p>
  </section>

  <section><h2>4. Refundable Deposit</h2>
    <p>Tenant shall provide a refundable deposit of <strong>{{security_deposit}}</strong>. The deposit shall be held in compliance with <em>N.C. Gen. Stat. § 42-51</em> (NC-licensed federally insured bank account or bond), with written notice of the institution to Tenant within 30 days. Return and itemization shall follow <em>§ 42-52</em>.</p>
    <p>The deposit shall not exceed the statutory cap in <em>§ 42-50</em> — one and one-half months' fee for terms longer than month-to-month.</p>
  </section>

  <section><h2>5. Term and Termination</h2>
    <p>This Agreement begins on <strong>{{lease_start_date}}</strong> and ends on <strong>{{lease_end_date}}</strong>. Either party may terminate a month-to-month arrangement upon <strong>seven (7) days' written notice</strong> per <em>N.C. Gen. Stat. § 42-14</em>. Termination does not authorize self-help removal; Operator must use judicial process if Tenant does not surrender possession.</p>
  </section>

  <section><h2>6. House Rules</h2>
    <p>Tenant agrees to abide by the following house rules:</p>
    <blockquote>{{co_living_rules}}</blockquote>
    <p>Operator may amend these rules upon 30 days' notice; amendments shall not unreasonably alter the core benefits of this Agreement.</p>
  </section>

  <section><h2>7. Occupants, Pets, Parking</h2>
    <p>Authorized occupants: {{occupants}}. Pets allowed: {{pets_allowed}}. Parking: {{parking}}. Guests may stay no longer than seven (7) consecutive nights without written consent.</p>
  </section>

  ${EARLY_TERMINATION_NC}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const TN_RESIDENTIAL: SeedTemplate = {
  state: "TN",
  category: "standard_residential",
  name: "Tennessee Residential Lease",
  description: "Standard residential lease grounded in the Tennessee URLTA (Title 66 Chapter 28) where applicable.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "payment_methods",
  ],
  citations: [
    "Tenn. Code Ann. § 29-18-101 et seq.", "Tenn. Code Ann. § 66-28-102",
    "Tenn. Code Ann. § 66-28-201", "Tenn. Code Ann. § 66-28-301",
    "Tenn. Code Ann. § 66-28-302", "Tenn. Code Ann. § 66-28-305",
    "Tenn. Code Ann. § 66-28-505", "Tenn. Code Ann. § 66-28-512",
    "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="TN" data-tenancy="residential">
  <header>
    <h1>Tennessee Residential Lease Agreement</h1>
    <p class="lease-subtitle">Governed by the Tennessee Uniform Residential Landlord and Tenant Act (URLTA), Tenn. Code Ann. § 66-28-101 et seq., where applicable. In non-URLTA counties (population ≤ 75,000 per § 66-28-102), the provisions of this Lease operate as contractual ceilings.</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
    <p><em>Landlord identifies themselves above as the person authorized to manage the Property and receive notices, pursuant to Tenn. Code Ann. § 66-28-302.</em></p>
  </section>

  <section><h2>2. Property</h2>
    <p>Premises located at <strong>{{property_address}}</strong>. Authorized occupants: {{occupants}}.</p>
  </section>

  <section><h2>3. Term</h2>
    <p>From <strong>{{lease_start_date}}</strong> through <strong>{{lease_end_date}}</strong>. Periodic month-to-month tenancies may be terminated by either party on <strong>thirty (30) days' written notice</strong> per <em>Tenn. Code Ann. § 66-28-512</em>.</p>
  </section>

  <section><h2>4. Rent</h2>
    <p>Tenant shall pay <strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong> of each month.</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
    <p><strong>Late fee.</strong> Pursuant to <em>§ 66-28-201(d)</em>, no late fee may be charged until rent is at least five (5) days past due, and the fee is capped at 10% of the past-due rent. For the rent above: <strong>{{late_fee}}</strong>.</p>
  </section>

  <section><h2>5. Security Deposit</h2>
    <p>Tenant shall deposit <strong>{{security_deposit}}</strong>. Tennessee URLTA does not cap the residential deposit. Pursuant to <em>§ 66-28-301(a)</em>, the deposit shall be held in a separate account, used solely for that purpose, at any bank or lending institution subject to regulation by the State of Tennessee or any agency of the United States government (an FDIC-insured bank in any state satisfies this requirement); Landlord shall inform Tenant in writing of the location of the institution at signing. Within 30 days of the end of tenancy, Landlord shall provide a written itemization of any deductions; if Tenant does not claim the balance within 60 days after Landlord sends notice, Landlord may remove the funds from the separate account.</p>
  </section>

  <section><h2>6. Utilities, Pets, Parking</h2>
    <p>Utilities included: {{utilities}}. Pets allowed: {{pets_allowed}}. Parking: {{parking}}.</p>
  </section>

  <section><h2>7. Default and Cure</h2>
    <p>Pursuant to <em>Tenn. Code Ann. § 66-28-505</em>, if Tenant materially breaches in a manner that may be cured by payment of rent, repair costs, or other amount due, Landlord may give Tenant written notice that the Lease will terminate if not cured within <strong>fourteen (14) days</strong> of receipt. For non-remediable breaches, the Lease shall terminate on a date not less than 14 days after notice.</p>
    <p><strong>Eviction procedure.</strong> Removal of Tenant from possession requires judicial process under Tennessee's Forcible Entry and Detainer statute (<em>Tenn. Code Ann. § 29-18-101 et seq.</em>) or URLTA where applicable. Landlord shall not use self-help under any circumstances.</p>
  </section>

  <section><h2>8. Landlord Access</h2>
    <p>Landlord may enter at reasonable times after giving Tenant at least 24 hours' notice, except in emergencies.</p>
  </section>

  <section><h2>9. Holdover and Automatic Month-to-Month Conversion</h2>
    <p>If Tenant remains in possession of the Property after expiration of the lease term with Landlord's consent (express or implied by continued acceptance of rent), this Lease shall automatically convert to a <strong>month-to-month tenancy</strong> on the same terms and conditions then in effect. Either party may terminate the resulting month-to-month tenancy by providing the other party written notice no less than <strong>thirty (30) days</strong> prior to the next periodic rental due date, as required by <em>Tenn. Code Ann. § 66-28-512</em>.</p>
    <p>If Tenant remains in possession without Landlord's consent after expiration of the term, Landlord may pursue removal through Tennessee's Forcible Entry and Detainer procedure, <em>Tenn. Code Ann. § 29-18-101 et seq.</em>, or through URLTA where applicable. Landlord shall not use self-help removal under any circumstances.</p>
  </section>

  <section><h2>10. Lease Renewal and Rent Adjustment</h2>
    <p><strong>Renewal offer.</strong> Prior to expiration of any fixed lease term, Landlord may offer Tenant a written renewal agreement. Any renewal may include a rent adjustment of up to <strong>three percent (3%)</strong> of the then-current monthly rent, provided Landlord delivers written notice of the new rent no less than <strong>sixty (60) days</strong> before the renewal term begins.</p>
    <p><strong>Ongoing 3% cap after 24 months.</strong> Beginning twenty-four (24) months after the Lease Start Date and on each subsequent twelve-month anniversary thereafter, Landlord reserves the right to increase the monthly rent by up to <strong>three percent (3%)</strong> of the then-current rent, upon <strong>sixty (60) days' written notice</strong>. No increase shall take effect during the first twenty-four (24) months of continuous tenancy regardless of any renewals or holdover conversions. Increases may compound annually but shall not exceed three percent (3%) per year.</p>
    <p>Tennessee has no statewide rent-control law; the three-percent ceiling is a voluntary contractual commitment by Landlord and is enforceable as a term of this Lease.</p>
  </section>

  ${EARLY_TERMINATION_TN}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const TN_COLIVING: SeedTemplate = {
  state: "TN",
  category: "coliving_room_rental",
  name: "Tennessee Co-Living / Room Rental Agreement",
  description: "Room-rental / membership agreement for co-living operators in Tennessee. Does NOT bypass eviction law.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "co_living_rules", "unit_or_room_label", "payment_methods",
  ],
  citations: [
    "Tenn. Code Ann. § 29-18-101 et seq.", "Tenn. Code Ann. § 66-28-201",
    "Tenn. Code Ann. § 66-28-301", "Tenn. Code Ann. § 66-28-505",
    "Tenn. Code Ann. § 66-28-512", "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="TN" data-tenancy="coliving_room_rental">
  <header>
    <h1>Tennessee Co-Living / Room Rental Agreement</h1>
    <p class="lease-subtitle">Room rental within a shared residence — Tennessee eviction procedure still applies</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Operator/Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Member/Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Nature of This Agreement</h2>
    <p>Tenant is granted the right to occupy <strong>{{unit_or_room_label}}</strong> at <strong>{{property_address}}</strong> and use the shared common areas. Operator may enter with 24 hours' notice (except in emergencies) and may reassign Tenant to a comparable room on 30 days' written notice.</p>
    <p>The "membership" or "room rental" framing applies to house rules and room assignment only. <strong>If Operator seeks to remove Tenant from possession, Operator will follow Tennessee's applicable eviction procedure (Tenn. Code Ann. § 29-18-101 et seq. or URLTA where applicable). Self-help removal is prohibited.</strong> Nothing in this Agreement waives any procedural protection or non-waivable right under Tennessee law.</p>
  </section>

  <section><h2>3. Monthly Fee</h2>
    <p><strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong>. Utilities included: {{utilities}}. Late fee: <strong>{{late_fee}}</strong> (capped at 10% of the past-due amount per Tenn. Code Ann. § 66-28-201(d) after the 5-day grace).</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
  </section>

  <section><h2>4. Refundable Deposit</h2>
    <p><strong>{{security_deposit}}</strong>, held in compliance with <em>Tenn. Code Ann. § 66-28-301(a)</em> (separate account at a bank or lending institution regulated by the State of Tennessee or any agency of the U.S. government — FDIC-insured banks in any state qualify — with written notice of the institution at signing).</p>
  </section>

  <section><h2>5. Term and Termination</h2>
    <p>From <strong>{{lease_start_date}}</strong> through <strong>{{lease_end_date}}</strong>. Either party may terminate a month-to-month arrangement on 30 days' written notice. Material-breach cure period of 14 days per <em>§ 66-28-505</em>.</p>
  </section>

  <section><h2>6. House Rules</h2>
    <blockquote>{{co_living_rules}}</blockquote>
    <p>Operator may amend on 30 days' notice; amendments shall not unreasonably alter the core benefits.</p>
  </section>

  <section><h2>7. Occupants, Pets, Parking</h2>
    <p>Authorized occupants: {{occupants}}. Pets: {{pets_allowed}}. Parking: {{parking}}.</p>
  </section>

  ${EARLY_TERMINATION_TN}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const GENERIC_MULTISTATE: SeedTemplate = {
  state: "ALL",
  category: "generic",
  name: "Multi-State Generic Lease",
  description: "Generic residential lease for use in states without a Leasely-curated template. State-specific protections and disclosures may not be reflected — independent attorney review is recommended.",
  variables: [
    "landlord_name", "tenant_name", "tenant_email", "property_address", "property_city",
    "state", "property_zip", "monthly_rent", "security_deposit", "lease_start_date",
    "lease_end_date", "rent_due_day", "late_fee", "utilities", "pets_allowed",
    "parking", "occupants", "payment_methods",
  ],
  citations: ["42 U.S.C. § 4852d"],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-template="generic">
  <header>
    <h1>Residential Lease Agreement</h1>
    <p class="lease-subtitle">For premises located in {{state}}</p>
  </header>

  <section class="legal-disclaimer" style="border-left:4px solid #c00;padding:8px 12px;background:#fff7f7;">
    <p><strong>Generic Template Warning.</strong> This document uses a multi-state generic template because Leasely does not yet maintain a curated template for {{state}}. State-specific protections, required disclosures, late-fee caps, security-deposit caps, and eviction procedures may differ materially from this document. An attorney licensed in {{state}} should review before reliance.</p>
  </section>

  <section><h2>1. Parties</h2>
    <p><strong>Landlord:</strong> {{landlord_name}}<br/><strong>Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Property</h2>
    <p>{{property_address}}. Authorized occupants: {{occupants}}.</p>
  </section>

  <section><h2>3. Term</h2>
    <p>From {{lease_start_date}} through {{lease_end_date}}.</p>
  </section>

  <section><h2>4. Rent</h2>
    <p>{{monthly_rent}} per month, due on the {{rent_due_day}} of each month. Late fee: {{late_fee}}.</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
  </section>

  <section><h2>5. Security Deposit</h2>
    <p>{{security_deposit}}, held in accordance with the applicable {{state}} law.</p>
  </section>

  <section><h2>6. Utilities, Pets, Parking</h2>
    <p>Utilities included: {{utilities}}. Pets allowed: {{pets_allowed}}. Parking: {{parking}}.</p>
  </section>

  <section><h2>7. Eviction Procedure</h2>
    <p>If Landlord seeks to recover possession of the Property, Landlord shall follow the eviction procedure required by the law of {{state}}. Self-help removal (lockouts, utility shutoffs, removal of property) is prohibited. Nothing in this Lease waives any procedural protection or non-waivable right the Tenant has under applicable law.</p>
  </section>

  ${EARLY_TERMINATION_GENERIC}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

export const SEED_TEMPLATES: SeedTemplate[] = [
  NC_RESIDENTIAL, NC_COLIVING, TN_RESIDENTIAL, TN_COLIVING, GENERIC_MULTISTATE,
];
