// Seed data for the state-specific lease templates.
//
// These are the *source-of-truth* template bodies. On server startup, the DB
// is checked for each (state, category) pair; if missing, the row is inserted
// here. Admin edits in the lease_template_versions table take precedence —
// the seed only runs when there is no active version yet.
//
// To add a new state without changing core code: append a new SeedTemplate
// entry here with its state code, category, body (with {{placeholders}}),
// citations, and disclosures. Run the server once and it appears in the UI.

export interface SeedTemplate {
  state: string;                                                      // "NC", "TN", "ALL"
  category: "standard_residential" | "coliving_room_rental" | "generic";
  name: string;
  description: string;
  bodyHtml: string;
  variables: string[];
  citations: string[];
  disclosures: string[];
}

const COMPLIANCE_BLOCK = `
<section class="legal-disclaimer">
  <p><strong>Legal Disclaimer.</strong> This lease was generated by Leasely from a state-specific template. Leasely is not a law firm and does not provide legal advice. The Landlord and Tenant should each consult an attorney licensed in {{state}} before signing if either has questions about their rights and obligations. Statutory citations are provided for reference only.</p>
</section>`;

const FEDERAL_LEAD_PAINT = `
<section>
  <h2>Federal Lead-Based Paint Disclosure</h2>
  <p>Housing built before 1978 may contain lead-based paint. If the Property was built before 1978, Landlord shall provide Tenant with the EPA pamphlet <em>"Protect Your Family From Lead in Your Home"</em> and any known information concerning lead-based paint or lead-based paint hazards, in compliance with 42 U.S.C. § 4852d and 24 CFR § 35.92.</p>
</section>`;

const SIGNATURE_BLOCK = `
<section>
  <h2>Signatures</h2>
  <div class="signature-block">
    <p><strong>Landlord:</strong> ____________________________ &nbsp; Date: ____________</p>
    <p><strong>Tenant:</strong> ____________________________ &nbsp; Date: ____________</p>
  </div>
</section>`;

// ─── Early Termination (Lease Break) ──────────────────────────────────────────
// State-specific buyout language. Two universal principles apply in every U.S.
// state: (1) the landlord has a duty to mitigate damages by making reasonable
// efforts to re-let, and (2) servicemembers may terminate under the SCRA
// (50 U.S.C. § 3955) with 30 days' notice + a copy of orders. State-specific
// statutory protections (domestic violence, habitability) are added per state.
const EARLY_TERMINATION_NC = `
<section>
  <h2>Early Termination by Tenant (Lease Break)</h2>
  <p><strong>Notice and fee.</strong> If Tenant wishes to end this Lease before the Lease End Date for any reason not protected by statute, Tenant shall (a) provide Landlord with at least <strong>sixty (60) days' written notice</strong> of the intended vacate date, and (b) pay an <strong>early-termination fee equal to two (2) months' rent</strong>, OR the rent that would be owed for the remainder of the term, <em>whichever is less</em>. The fee is in addition to any unpaid rent, damages beyond ordinary wear and tear, and lawful deductions from the security deposit under <em>N.C. Gen. Stat. § 42-51 and § 42-52</em>.</p>
  <p><strong>Landlord's duty to mitigate.</strong> If Tenant vacates before the term ends, Landlord shall make reasonable efforts to re-let the Property at a comparable rent. Tenant remains liable for rent only until the Property is re-let to a replacement tenant or the original Lease End Date, whichever comes first, less Landlord's reasonable re-letting costs (advertising, showings, screening, broker fees if any). North Carolina recognizes a landlord's mitigation duty in residential leases; this clause restates that duty for clarity.</p>
  <p><strong>Statutorily protected terminations.</strong> Tenant may terminate without paying the early-termination fee in the following situations, each of which has its own notice and documentation requirements:</p>
  <ul>
    <li><strong>Active military service (SCRA).</strong> Under the federal Servicemembers Civil Relief Act, <em>50 U.S.C. § 3955</em>, a servicemember who enters active duty or receives PCS / deployment orders of 90+ days may terminate by giving Landlord written notice with a copy of orders; the Lease terminates 30 days after the next rent due date.</li>
    <li><strong>Domestic violence, sexual assault, or stalking.</strong> Pursuant to <em>N.C. Gen. Stat. § 42-45.1</em>, a victim with a valid protective order, criminal restraining order, or qualifying court order or law-enforcement documentation may terminate the Lease by giving Landlord 30 days' written notice. Tenant is liable only for rent through the termination date.</li>
    <li><strong>Uninhabitable premises.</strong> If Landlord fails to comply with the duties imposed by <em>N.C. Gen. Stat. § 42-42</em> after written notice and a reasonable opportunity to cure, Tenant may pursue the remedies available under § 42-44, which may include termination in certain circumstances.</li>
  </ul>
  <p><strong>Security deposit.</strong> The security deposit may be applied to unpaid rent, the early-termination fee, and damages beyond ordinary wear and tear, in accordance with <em>N.C. Gen. Stat. § 42-51</em>. Any balance shall be returned within 30 days (or 60 days if a final accounting is required) per <em>§ 42-52</em>.</p>
</section>`;

const EARLY_TERMINATION_TN = `
<section>
  <h2>Early Termination by Tenant (Lease Break)</h2>
  <p><strong>Notice and fee.</strong> If Tenant wishes to end this Lease before the Lease End Date for any reason not protected by statute, Tenant shall (a) provide Landlord with at least <strong>sixty (60) days' written notice</strong> of the intended vacate date, and (b) pay an <strong>early-termination fee equal to two (2) months' rent</strong>, OR the rent that would be owed for the remainder of the term, <em>whichever is less</em>. The fee is in addition to any unpaid rent, damages beyond ordinary wear and tear, and lawful deductions from the security deposit under <em>Tenn. Code Ann. § 66-28-301 and § 66-28-305</em>.</p>
  <p><strong>Landlord's duty to mitigate.</strong> If Tenant vacates before the term ends, Landlord shall make reasonable efforts to re-let the Property at a comparable rent. In URLTA counties, this duty is codified at <em>Tenn. Code Ann. § 66-28-507</em>. Tenant remains liable for rent only until the Property is re-let or the original Lease End Date, whichever comes first, less Landlord's reasonable re-letting costs.</p>
  <p><strong>Statutorily protected terminations.</strong> Tenant may terminate without paying the early-termination fee in the following situations, each of which has its own notice and documentation requirements:</p>
  <ul>
    <li><strong>Active military service (SCRA).</strong> Under <em>50 U.S.C. § 3955</em>, a servicemember entering active duty or receiving PCS / deployment orders of 90+ days may terminate by giving Landlord written notice with a copy of orders; the Lease terminates 30 days after the next rent due date.</li>
    <li><strong>Domestic violence, sexual assault, or stalking.</strong> Pursuant to <em>Tenn. Code Ann. § 66-7-109</em>, a victim with a qualifying protective order or other documentation specified by statute may terminate the Lease by giving Landlord at least 30 days' written notice. Tenant is liable only for rent and damages accruing through the termination date.</li>
    <li><strong>Uninhabitable premises (URLTA counties).</strong> If Landlord fails to comply with <em>Tenn. Code Ann. § 66-28-304</em> after the 14-day cure notice required by <em>§ 66-28-501</em>, Tenant may terminate without further obligation. In non-URLTA counties this remedy is contractual rather than statutory but Landlord agrees to honor it.</li>
  </ul>
  <p><strong>Security deposit.</strong> The security deposit may be applied to unpaid rent, the early-termination fee, and damages beyond ordinary wear and tear, in accordance with <em>Tenn. Code Ann. § 66-28-301(g)</em>. Final accounting and any balance shall be provided within 30 days of the termination date.</p>
</section>`;

const EARLY_TERMINATION_GENERIC = `
<section>
  <h2>Early Termination by Tenant (Lease Break)</h2>
  <p><strong>Notice and fee.</strong> If Tenant wishes to end this Lease before the Lease End Date for any reason not protected by statute, Tenant shall (a) provide Landlord with at least <strong>sixty (60) days' written notice</strong> of the intended vacate date, and (b) pay an <strong>early-termination fee equal to two (2) months' rent</strong>, OR the rent that would be owed for the remainder of the term, <em>whichever is less</em>. The fee is in addition to any unpaid rent, damages beyond ordinary wear and tear, and lawful deductions from the security deposit.</p>
  <p><strong>Landlord's duty to mitigate.</strong> Nearly every U.S. state — by statute or by case law — requires Landlord to make reasonable efforts to re-let the Property after Tenant vacates. Tenant remains liable for rent only until the Property is re-let to a replacement tenant or the original Lease End Date, whichever comes first, less Landlord's reasonable re-letting costs.</p>
  <p><strong>Statutorily protected terminations.</strong> Tenant may terminate without paying the early-termination fee in the following situations (each with its own notice and documentation requirements under {{state}} law):</p>
  <ul>
    <li><strong>Active military service (SCRA).</strong> Under <em>50 U.S.C. § 3955</em>, a servicemember entering active duty or receiving PCS / deployment orders of 90+ days may terminate by giving Landlord written notice with a copy of orders.</li>
    <li><strong>Domestic violence, sexual assault, or stalking.</strong> Most states permit a victim with a qualifying protective order or court documentation to terminate on 30 days' written notice. The exact statute and documentation required vary by state — Tenant should consult {{state}} law.</li>
    <li><strong>Uninhabitable premises.</strong> If Landlord materially fails to maintain the Property in habitable condition after written notice and a reasonable opportunity to cure, Tenant may have a statutory or common-law right to terminate.</li>
  </ul>
  <p><strong>Security deposit.</strong> The security deposit may be applied to unpaid rent, the early-termination fee, and damages beyond ordinary wear and tear, in accordance with applicable {{state}} law. Final accounting timing varies by state (commonly 14 to 30 days).</p>
</section>`;

const NC_RESIDENTIAL: SeedTemplate = {
  state: "NC",
  category: "standard_residential",
  name: "North Carolina Residential Lease",
  description: "Standard residential lease grounded in N.C. Gen. Stat. Chapter 42.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "payment_methods",
  ],
  citations: [
    "N.C. Gen. Stat. § 42-3", "N.C. Gen. Stat. § 42-14", "N.C. Gen. Stat. § 42-25.6",
    "N.C. Gen. Stat. § 42-26", "N.C. Gen. Stat. § 42-42", "N.C. Gen. Stat. § 42-43",
    "N.C. Gen. Stat. § 42-46", "N.C. Gen. Stat. § 42-46(e)", "N.C. Gen. Stat. § 42-46(f)",
    "N.C. Gen. Stat. § 42-46(g)", "N.C. Gen. Stat. § 42-46(i)(3)", "N.C. Gen. Stat. § 42-46(i)(5)",
    "N.C. Gen. Stat. § 42-50", "N.C. Gen. Stat. § 42-51", "N.C. Gen. Stat. § 42-52",
    "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="NC" data-tenancy="residential">
  <header>
    <h1>North Carolina Residential Lease Agreement</h1>
    <p class="lease-subtitle">Governed by N.C. Gen. Stat. Chapter 42</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Property</h2>
    <p>Landlord leases to Tenant the residential premises located at <strong>{{property_address}}</strong> (the "Property"). Authorized occupants: {{occupants}}.</p>
  </section>

  <section><h2>3. Term</h2>
    <p>This Lease begins on <strong>{{lease_start_date}}</strong> and ends on <strong>{{lease_end_date}}</strong>. Either party may terminate a month-to-month tenancy by giving written notice at least <strong>seven (7) days</strong> before the end of the rental period, in accordance with <em>N.C. Gen. Stat. § 42-14</em>.</p>
  </section>

  <section><h2>4. Rent</h2>
    <p>Tenant shall pay rent of <strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong> of each month.</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
    <p><strong>Late fee.</strong> If any rental payment is five (5) or more calendar days late, Landlord may charge a late fee of <strong>{{late_fee}}</strong>, not to exceed the greater of $15.00 or 5% of the monthly rent under <em>N.C. Gen. Stat. § 42-46(a)</em>.</p>
  </section>

  <section><h2>5. Security Deposit</h2>
    <p>Tenant shall deposit <strong>{{security_deposit}}</strong>. Pursuant to <em>N.C. Gen. Stat. § 42-50</em>, the deposit may not exceed 1.5 months' rent for terms longer than month-to-month, one month's rent for month-to-month, or one week's rent for weekly tenancies.</p>
    <p>Pursuant to <em>§ 42-51</em>, the deposit shall be held in a trust account with a licensed and federally insured depository institution located in North Carolina, or secured by a bond. Landlord shall furnish Tenant with written notice of the name and address of the institution holding the deposit within <strong>thirty (30) days</strong> of the beginning of the lease term.</p>
    <p>Within <strong>thirty (30) days</strong> after termination of the tenancy (or <strong>sixty (60) days</strong> if a final accounting requires additional time), Landlord shall provide Tenant with an itemized accounting of any deductions and return the balance, in accordance with <em>§ 42-52</em>.</p>
  </section>

  <section><h2>6. Utilities</h2>
    <p>Utilities included: {{utilities}}. Utilities not listed are the responsibility of Tenant.</p>
  </section>

  <section><h2>7. Pets and Pet Fee</h2>
    <p>Pets allowed: {{pets_allowed}}. Any pet fee charged is non-refundable and is in addition to (not part of) the security deposit.</p>
  </section>

  <section><h2>8. Parking</h2>
    <p>{{parking}}</p>
  </section>

  <section><h2>9. Landlord Duties</h2>
    <p>Landlord shall comply with the duties imposed by <em>N.C. Gen. Stat. § 42-42</em>, including keeping the Property fit and habitable, complying with building and housing codes, making necessary repairs, and maintaining electrical, plumbing, sanitary, heating, ventilating, and air-conditioning facilities in good and safe working order.</p>
  </section>

  <section><h2>10. Tenant Duties</h2>
    <p>Tenant shall comply with <em>N.C. Gen. Stat. § 42-43</em>, including keeping the Property clean and safe, disposing of garbage properly, not damaging the Property, and not disturbing neighbors.</p>
  </section>

  <section><h2>11. Default, Cure, and Eviction</h2>
    <p><strong>Nonpayment of rent.</strong> If Tenant fails to pay rent when due and remains in default after lawful demand, Landlord may seek summary ejectment under <em>N.C. Gen. Stat. § 42-3</em> and <em>§ 42-26(a)(1)</em>. Eviction in North Carolina is by judicial process under § 42-25.6 et seq.; Landlord shall not use self-help (lockout, utility shutoff, or removal of property) under any circumstances.</p>
    <p><strong>Material breach.</strong> If Tenant materially breaches any other term of this Lease, Landlord shall give Tenant <strong>ten (10) days' written notice</strong> to cure (a contractual courtesy beyond what § 42-26 statutorily requires) before initiating summary ejectment under <em>§ 42-26(a)(2)</em>.</p>
    <p>Nothing in this Lease waives any non-waivable right of Tenant under North Carolina law.</p>
  </section>

  <section><h2>12. Fees Recoverable Under N.C. Gen. Stat. § 42-46</h2>
    <ul>
      <li><strong>Complaint-filing fee.</strong> If Landlord files a complaint for summary ejectment, Landlord may collect a complaint-filing fee not to exceed the greater of $15 or 5% of the monthly rent under <em>§ 42-46(e)</em>. This fee shall be refunded if the complaint is dismissed because Tenant cures the default.</li>
      <li><strong>Court-appearance fee.</strong> If Landlord prevails in small claims court, Landlord may collect a court-appearance fee not to exceed 10% of the monthly rent under <em>§ 42-46(f)</em>.</li>
      <li><strong>Second-trial fee.</strong> If Landlord prevails on appeal from a magistrate's judgment, Landlord may collect a second-trial fee not to exceed 12% of the monthly rent under <em>§ 42-46(g)</em>.</li>
      <li><strong>Reasonable attorney's fees.</strong> Pursuant to <em>§ 42-46(i)(3)</em>, Landlord may recover reasonable attorney's fees actually paid or owed, not to exceed 15% of the amount owed by Tenant, or 15% of the monthly rent if the eviction is based on a default other than nonpayment of rent.</li>
      <li><strong>Frivolous-appeal attorney's fees.</strong> If Tenant appeals a summary ejectment to district court and the court finds the appeal frivolous, unreasonable, without foundation, in bad faith, or solely for delay, Landlord may recover all actual reasonable attorney's fees under <em>§ 42-46(i)(5)</em>.</li>
    </ul>
  </section>

  ${EARLY_TERMINATION_NC}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const NC_COLIVING: SeedTemplate = {
  state: "NC",
  category: "coliving_room_rental",
  name: "North Carolina Co-Living / Room Rental Agreement",
  description: "Room-rental / membership agreement for co-living operators in North Carolina. Does NOT bypass eviction law.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "co_living_rules", "unit_or_room_label", "payment_methods",
  ],
  citations: [
    "N.C. Gen. Stat. § 42-14", "N.C. Gen. Stat. § 42-25.6", "N.C. Gen. Stat. § 42-26",
    "N.C. Gen. Stat. § 42-46", "N.C. Gen. Stat. § 42-50", "N.C. Gen. Stat. § 42-51",
    "N.C. Gen. Stat. § 42-52", "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="NC" data-tenancy="coliving_room_rental">
  <header>
    <h1>North Carolina Co-Living / Room Rental Agreement</h1>
    <p class="lease-subtitle">Room rental within a shared residence — eviction procedure under N.C. Gen. Stat. § 42 still applies</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Operator/Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Member/Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Nature of This Agreement</h2>
    <p>Tenant is granted the right to occupy <strong>{{unit_or_room_label}}</strong> at <strong>{{property_address}}</strong> (the "Residence") and to use the shared common areas. Operator reserves the right to enter the room with 24 hours' notice (except in emergencies) and may reassign Tenant to a comparable room within the Residence on 30 days' written notice.</p>
    <p>The "membership" or "room rental" framing applies to house rules and room assignment only. <strong>If Operator seeks to remove Tenant from possession, Operator will follow the applicable North Carolina eviction procedure (summary ejectment under N.C. Gen. Stat. § 42-25.6 et seq.) and will not engage in any self-help removal.</strong> Nothing in this Agreement waives any procedural protection or non-waivable right under North Carolina law.</p>
  </section>

  <section><h2>3. Monthly Fee</h2>
    <p>Tenant shall pay <strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong> of each month. The fee covers the right to occupy {{unit_or_room_label}}, use of common areas, and shared utilities ({{utilities}}).</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
    <p>Late fee: <strong>{{late_fee}}</strong>, not to exceed the greater of $15 or 5% of the monthly fee per <em>N.C. Gen. Stat. § 42-46(a)</em>.</p>
  </section>

  <section><h2>4. Refundable Deposit</h2>
    <p>Tenant shall provide a refundable deposit of <strong>{{security_deposit}}</strong>. The deposit shall be held in compliance with <em>N.C. Gen. Stat. § 42-51</em> (NC-licensed federally insured bank account or bond), with written notice of the institution to Tenant within 30 days. Return and itemization shall follow <em>§ 42-52</em>.</p>
    <p>The deposit shall not exceed the statutory cap in <em>§ 42-50</em> — one and one-half months' fee for terms longer than month-to-month.</p>
  </section>

  <section><h2>5. Term and Termination</h2>
    <p>This Agreement begins on <strong>{{lease_start_date}}</strong> and ends on <strong>{{lease_end_date}}</strong>. Either party may terminate a month-to-month arrangement upon <strong>seven (7) days' written notice</strong> per <em>N.C. Gen. Stat. § 42-14</em>. Termination does not authorize self-help removal; Operator must use judicial process if Tenant does not surrender possession.</p>
  </section>

  <section><h2>6. House Rules</h2>
    <p>Tenant agrees to abide by the following house rules:</p>
    <blockquote>{{co_living_rules}}</blockquote>
    <p>Operator may amend these rules upon 30 days' notice; amendments shall not unreasonably alter the core benefits of this Agreement.</p>
  </section>

  <section><h2>7. Occupants, Pets, Parking</h2>
    <p>Authorized occupants: {{occupants}}. Pets allowed: {{pets_allowed}}. Parking: {{parking}}. Guests may stay no longer than seven (7) consecutive nights without written consent.</p>
  </section>

  ${EARLY_TERMINATION_NC}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const TN_RESIDENTIAL: SeedTemplate = {
  state: "TN",
  category: "standard_residential",
  name: "Tennessee Residential Lease",
  description: "Comprehensive residential lease for Tennessee grounded in URLTA (Title 66 Chapter 28) plus statewide statutes — covers parties, term, rent, deposit, inspections, tenant alterations, utilities, insurance, attorney fees, assignment, damage, care/use, notice address, holdover, early termination, and signatures.",
  variables: [
    "landlord_name", "landlord_address", "landlord_phone", "landlord_email",
    "tenant_name", "tenant_email", "tenant_phone",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "payment_methods",
  ],
  citations: [
    "Tenn. Code Ann. § 29-18-101 et seq.", "Tenn. Code Ann. § 66-7-109",
    "Tenn. Code Ann. § 66-28-102", "Tenn. Code Ann. § 66-28-201",
    "Tenn. Code Ann. § 66-28-301", "Tenn. Code Ann. § 66-28-302",
    "Tenn. Code Ann. § 66-28-304", "Tenn. Code Ann. § 66-28-305",
    "Tenn. Code Ann. § 66-28-403", "Tenn. Code Ann. § 66-28-501",
    "Tenn. Code Ann. § 66-28-505", "Tenn. Code Ann. § 66-28-507",
    "Tenn. Code Ann. § 66-28-512", "50 U.S.C. § 3955",
    "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="TN" data-tenancy="residential">
  <header>
    <h1>Tennessee Residential Lease Agreement</h1>
    <p class="lease-subtitle">Governed by the Tennessee Uniform Residential Landlord and Tenant Act (URLTA), Tenn. Code Ann. § 66-28-101 et seq., where applicable. In non-URLTA counties (population ≤ 75,000 per § 66-28-102), the provisions of this Lease operate as contractual ceilings.</p>
    <p class="lease-preamble"><strong>This Lease (the "Lease") is entered into between {{landlord_name}} ("Landlord") and {{tenant_name}} ("Tenant") (each a "Party" and together the "Parties").</strong> In consideration of the Landlord renting the premises described below to the Tenant, and other valuable consideration, the receipt and sufficiency of which the Parties acknowledge, the Parties agree as follows.</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
    <p><em>Landlord identifies themselves above as the person authorized to manage the Property and receive notices, pursuant to Tenn. Code Ann. § 66-28-302.</em></p>
  </section>

  <section><h2>2. Property</h2>
    <p>Premises located at <strong>{{property_address}}</strong>. Authorized occupants: {{occupants}}.</p>
  </section>

  <section><h2>3. Term</h2>
    <p>From <strong>{{lease_start_date}}</strong> through <strong>{{lease_end_date}}</strong>. Periodic month-to-month tenancies may be terminated by either party on <strong>thirty (30) days' written notice</strong> per <em>Tenn. Code Ann. § 66-28-512</em>.</p>
  </section>

  <section><h2>4. Rent</h2>
    <p>Tenant shall pay <strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong> of each month.</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
    <p><strong>Late fee.</strong> Pursuant to <em>§ 66-28-201(d)</em>, no late fee may be charged until rent is at least five (5) days past due, and the fee is capped at 10% of the past-due rent. For the rent above: <strong>{{late_fee}}</strong>.</p>
  </section>

  <section><h2>5. Security Deposit</h2>
    <p>Tenant shall deposit <strong>{{security_deposit}}</strong>. Tennessee URLTA does not cap the residential deposit. Pursuant to <em>§ 66-28-301(a)</em>, the deposit shall be held in a separate account, used solely for that purpose, at any bank or lending institution subject to regulation by the State of Tennessee or any agency of the United States government (an FDIC-insured bank in any state satisfies this requirement); Landlord shall inform Tenant in writing of the location of the institution at signing. Within 30 days of the end of tenancy, Landlord shall provide a written itemization of any deductions; if Tenant does not claim the balance within 60 days after Landlord sends notice, Landlord may remove the funds from the separate account.</p>
  </section>

  <section><h2>6. Utilities, Pets, Parking</h2>
    <p>Utilities included: {{utilities}}. Pets allowed: {{pets_allowed}}. Parking: {{parking}}.</p>
  </section>

  <section><h2>7. Default and Cure</h2>
    <p>Pursuant to <em>Tenn. Code Ann. § 66-28-505</em>, if Tenant materially breaches in a manner that may be cured by payment of rent, repair costs, or other amount due, Landlord may give Tenant written notice that the Lease will terminate if not cured within <strong>fourteen (14) days</strong> of receipt. For non-remediable breaches, the Lease shall terminate on a date not less than 14 days after notice.</p>
    <p><strong>Eviction procedure.</strong> Removal of Tenant from possession requires judicial process under Tennessee's Forcible Entry and Detainer statute (<em>Tenn. Code Ann. § 29-18-101 et seq.</em>) or URLTA where applicable. Landlord shall not use self-help under any circumstances.</p>
  </section>

  <section><h2>8. Landlord Access</h2>
    <p>Landlord may enter at reasonable times after giving Tenant at least 24 hours' notice, except in emergencies.</p>
  </section>

  <section><h2>9. Holdover and Automatic Month-to-Month Conversion</h2>
    <p>If Tenant remains in possession of the Property after expiration of the lease term with Landlord's consent (express or implied by continued acceptance of rent), this Lease shall automatically convert to a <strong>month-to-month tenancy</strong> on the same terms and conditions then in effect. Either party may terminate the resulting month-to-month tenancy by providing the other party written notice no less than <strong>thirty (30) days</strong> prior to the next periodic rental due date, as required by <em>Tenn. Code Ann. § 66-28-512</em>.</p>
    <p>If Tenant remains in possession without Landlord's consent after expiration of the term, Landlord may pursue removal through Tennessee's Forcible Entry and Detainer procedure, <em>Tenn. Code Ann. § 29-18-101 et seq.</em>, or through URLTA where applicable. Landlord shall not use self-help removal under any circumstances.</p>
  </section>

  <section><h2>10. Lease Renewal and Rent Adjustment</h2>
    <p><strong>Renewal offer.</strong> Prior to expiration of any fixed lease term, Landlord may offer Tenant a written renewal agreement. Any renewal may include a rent adjustment of up to <strong>three percent (3%)</strong> of the then-current monthly rent, provided Landlord delivers written notice of the new rent no less than <strong>sixty (60) days</strong> before the renewal term begins.</p>
    <p><strong>Ongoing 3% cap after 24 months.</strong> Beginning twenty-four (24) months after the Lease Start Date and on each subsequent twelve-month anniversary thereafter, Landlord reserves the right to increase the monthly rent by up to <strong>three percent (3%)</strong> of the then-current rent, upon <strong>sixty (60) days' written notice</strong>. No increase shall take effect during the first twenty-four (24) months of continuous tenancy regardless of any renewals or holdover conversions. Increases may compound annually but shall not exceed three percent (3%) per year.</p>
    <p>Tennessee has no statewide rent-control law; the three-percent ceiling is a voluntary contractual commitment by Landlord and is enforceable as a term of this Lease.</p>
  </section>

  <section><h2>11. Move-In and Move-Out Inspections</h2>
    <p>The Parties shall jointly complete, sign, and date a written inspection report describing the condition of the Property at the beginning of the tenancy and again at the end. Photographs taken at move-in and move-out are part of the inspection record. Any item not noted at move-in is presumed to have been in good condition at the start of the tenancy.</p>
  </section>

  <section><h2>12. Landlord Access</h2>
    <p>At reasonable times during the term of this Lease and any renewal, Landlord and Landlord's agents may enter the Property to (a) inspect the premises, (b) make necessary or agreed repairs, or (c) show the Property to prospective tenants or purchasers. Except in emergencies or with Tenant's consent, Landlord shall give Tenant at least <strong>twenty-four (24) hours' written or electronic notice</strong> before entering, consistent with the spirit of <em>Tenn. Code Ann. § 66-28-403</em>. Tenant shall not unreasonably withhold consent.</p>
  </section>

  <section><h2>13. Alterations and Tenant Improvements</h2>
    <p>Tenant shall obtain Landlord's prior written consent before doing any of the following on or to the Property:</p>
    <ol type="a">
      <li>Applying adhesive materials, or driving nails or hooks into walls or ceilings, beyond two small picture hooks per wall;</li>
      <li>Painting, wallpapering, redecorating, or otherwise materially altering the appearance of the Property;</li>
      <li>Removing or adding walls, or making any structural alteration;</li>
      <li>Installing a waterbed, in-wall safe, hot tub, or similar high-load fixture;</li>
      <li>Adding or modifying electrical wiring, gas lines, or heating units, or materially changing the amount of electrical or HVAC load drawn at the Property;</li>
      <li>Displaying placards, signs, or notices for advertising or commercial purposes on or visible from the exterior of the Property;</li>
      <li>Affixing or erecting a satellite dish, antenna, or tower on or near the Property except as permitted by the FCC Over-the-Air Reception Devices Rule, 47 CFR § 1.4000.</li>
    </ol>
    <p>Any alteration made without Landlord's consent may be reversed at Tenant's expense, and Landlord may deduct the reasonable cost of restoration from the security deposit per <em>Tenn. Code Ann. § 66-28-301(g)</em>.</p>
  </section>

  <section><h2>14. Insurance</h2>
    <p>Tenant acknowledges that Tenant's personal property is <strong>not insured by Landlord</strong> against damage, theft, fire, water intrusion, or any other loss, and that Landlord assumes no liability for any such loss. Tenant is strongly encouraged to obtain renter's insurance (typically &lt;$20/month) covering personal property and liability. Tenant is not required to insure Landlord's contents, furnishings, or the structure of the Property.</p>
  </section>

  <section><h2>15. Attorney Fees and Court Costs</h2>
    <p>If either Party files an action arising out of this Lease, the prevailing Party shall be entitled to recover from the non-prevailing Party, in addition to all sums otherwise owed, the reasonable attorney fees actually incurred and taxable court costs, subject to any cap or fee-shifting rule imposed by Tennessee law in the specific case.</p>
  </section>

  <section><h2>16. Governing Law and Forum</h2>
    <p>This Lease shall be construed in accordance with and exclusively governed by the laws of the State of Tennessee, without regard to its conflict-of-laws principles. The Parties consent to exclusive jurisdiction and venue in the state courts of general or specialized jurisdiction located in the Tennessee county where the Property is situated.</p>
  </section>

  <section><h2>17. Severability and Conflict with Statute</h2>
    <p>If any provision of this Lease conflicts with a non-waivable provision of URLTA or other applicable Tennessee law, the statutory provision controls and the conflicting Lease provision is reformed to the minimum extent necessary to comply. All other provisions remain in full force. Any provision required by statute is incorporated by reference even if not expressly stated above.</p>
  </section>

  <section><h2>18. Amendment</h2>
    <p>This Lease may be amended only by a written instrument signed by both Parties. Oral modifications are not binding. An exchange of signed electronic documents (including signed emails) is treated as a writing for this purpose.</p>
  </section>

  <section><h2>19. Assignment and Subletting</h2>
    <p>Tenant shall not assign this Lease, sublet the Property in whole or in part, or grant any license or concession to use the Property, without Landlord's prior written consent. Landlord may withhold consent in Landlord's reasonable discretion. Consent to one assignment, sublet, license, or concession is not consent to any subsequent assignment, sublet, license, or concession. Any purported assignment, sublet, license, or concession in violation of this section is voidable at Landlord's option and may, at Landlord's election, terminate this Lease subject to the eviction procedure required by Tennessee law.</p>
  </section>

  <section><h2>20. Damage to the Property</h2>
    <p>If the Property is materially damaged or destroyed by fire, storm, or other casualty <em>not caused by</em> Tenant's negligence or willful act (or that of Tenant's household, guests, or invitees), and Landlord elects not to rebuild or repair within a reasonable time, Landlord may terminate this Lease on written notice, with rent prorated to the date Tenant surrenders possession. If the casualty makes the Property uninhabitable, Tenant has the same termination right, on written notice to Landlord.</p>
    <p>Tenant shall promptly notify Landlord in writing of any damage to the Property or any condition that may significantly interfere with the normal use of the Property or any landlord-supplied furnishings, including water intrusion, plumbing failures, HVAC failure, electrical hazards, and visible mold growth.</p>
  </section>

  <section><h2>21. Care and Use of the Property</h2>
    <ol>
      <li>Tenant shall keep the Property clean and safe, and shall use all appliances, fixtures, and systems only for their intended purposes.</li>
      <li>Tenant shall not engage in or permit any illegal trade, activity, or substance manufacture on or about the Property. Possession or use of any controlled substance in violation of state or federal law is prohibited.</li>
      <li>The Parties shall comply with all applicable health, sanitation, fire, housing, and safety codes.</li>
      <li>The Parties shall use reasonable efforts to prevent the accumulation of moisture and the growth of mold. Tenant shall promptly notify Landlord in writing of any visible mold or persistent moisture; Landlord shall promptly respond.</li>
      <li>If the Property will be unoccupied for four (4) consecutive days or more, Tenant shall arrange a competent person to check on the Property periodically and shall provide Landlord with the name and contact information of that person in advance.</li>
      <li>At the end of the term, Tenant shall surrender the Property in substantially the same condition as at the start, ordinary wear and tear excepted.</li>
    </ol>
  </section>

  <section><h2>22. Smoking, Vaping, and Drug-Free Premises</h2>
    <p>Tenant and Tenant's household, guests, and invitees shall not smoke any substance (including but not limited to tobacco, cannabis, and herbal products) anywhere inside the Property. The same prohibition applies to vaping and e-cigarettes inside the Property. Smoking and vaping outside, on porches and balconies, are permitted only if local ordinance allows and shall not direct smoke into neighboring units. Violation is a material breach and may result in odor-remediation charges deducted from the security deposit.</p>
  </section>

  <section><h2>23. Rules and Regulations; Locks</h2>
    <p>Tenant shall comply with all reasonable house rules and posted regulations governing the Property and any associated common areas. Tenant shall not change, add, or rekey locks without Landlord's prior written consent, except as expressly permitted by Tennessee law (including without limitation a victim's right to change locks under <em>Tenn. Code Ann. § 66-28-518</em>). Tenant shall provide Landlord with a working key or code to any lock Tenant has changed with consent.</p>
  </section>

  <section><h2>24. Joint and Several Liability</h2>
    <p>If more than one person signs this Lease as Tenant, each is jointly and severally liable for all obligations of Tenant, including rent, damages, late fees, and attorney fees. Landlord may proceed against any one or all Tenants for the full amount of any obligation.</p>
  </section>

  <section><h2>25. Holdover and Month-to-Month Conversion</h2>
    <p>If Tenant remains in possession after the Lease End Date with Landlord's express or implied consent (including by continued acceptance of rent), this Lease automatically converts to a <strong>month-to-month tenancy</strong> on the same terms then in effect, subject to any rent adjustment lawfully noticed under Section 10. Either Party may then terminate on at least thirty (30) days' written notice ending on the next periodic rent due date, per <em>Tenn. Code Ann. § 66-28-512</em>. If Tenant remains without consent, Landlord may pursue removal through the Forcible Entry and Detainer process (<em>Tenn. Code Ann. § 29-18-101 et seq.</em>) or URLTA where applicable. Self-help removal is prohibited.</p>
  </section>

  <section><h2>26. Notices and Addresses for Service</h2>
    <p>For all matters relating to this tenancy, notices and demands shall be delivered as follows. Each Party may update the contact information below by written notice to the other.</p>
    <p><strong>Landlord:</strong> {{landlord_name}}<br/>
       Address: {{landlord_address}}<br/>
       Phone: {{landlord_phone}}<br/>
       Email: {{landlord_email}}</p>
    <p><strong>Tenant:</strong> {{tenant_name}}<br/>
       Address: At the Property, unless changed by written notice<br/>
       Phone: {{tenant_phone}}<br/>
       Email: {{tenant_email}}</p>
    <p>Notice by email is effective on the day sent if sent before 5:00 p.m. local time and not bounced. Notice by U.S. mail is effective on the third business day after deposit, postage prepaid, addressed to the recipient at the address above.</p>
  </section>

  <section><h2>27. General Provisions</h2>
    <ol>
      <li>All monetary amounts in this Lease are denominated in U.S. dollars.</li>
      <li>A waiver of any breach by either Party is not a waiver of any subsequent breach.</li>
      <li>This Lease binds and benefits the Parties' respective heirs, executors, administrators, successors, and permitted assigns.</li>
      <li>Headings are for convenience only and do not affect interpretation. Singular includes plural and vice versa; gendered terms are inclusive.</li>
      <li>This Lease may be executed in counterparts, including electronic signatures and emailed PDFs, each of which is an original and all of which constitute one instrument.</li>
      <li>During the final thirty (30) days of the term, Landlord may post the customary "For Rent" or "For Sale" sign at the Property and may show the Property to prospective tenants or purchasers subject to the notice requirement in Section 12.</li>
      <li>Time is of the essence as to every provision of this Lease.</li>
      <li>This Lease, together with any written addenda signed by both Parties, constitutes the entire agreement and supersedes any prior oral or written understandings.</li>
    </ol>
  </section>

  ${EARLY_TERMINATION_TN}

  <section><h2>Acknowledgement of Duplicate</h2>
    <p>Tenant acknowledges receiving a duplicate copy of this fully executed Lease signed by both Tenant and Landlord on the date of full execution.</p>
  </section>

  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const TN_COLIVING: SeedTemplate = {
  state: "TN",
  category: "coliving_room_rental",
  name: "Tennessee Co-Living / Room Rental Agreement",
  description: "Room-rental / membership agreement for co-living operators in Tennessee. Does NOT bypass eviction law.",
  variables: [
    "landlord_name", "landlord_address", "tenant_name", "tenant_email",
    "property_address", "property_city", "state", "property_zip",
    "monthly_rent", "security_deposit", "lease_start_date", "lease_end_date",
    "rent_due_day", "late_fee", "utilities", "pets_allowed", "parking", "occupants",
    "co_living_rules", "unit_or_room_label", "payment_methods",
  ],
  citations: [
    "Tenn. Code Ann. § 29-18-101 et seq.", "Tenn. Code Ann. § 66-28-201",
    "Tenn. Code Ann. § 66-28-301", "Tenn. Code Ann. § 66-28-505",
    "Tenn. Code Ann. § 66-28-512", "42 U.S.C. § 4852d",
  ],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-state="TN" data-tenancy="coliving_room_rental">
  <header>
    <h1>Tennessee Co-Living / Room Rental Agreement</h1>
    <p class="lease-subtitle">Room rental within a shared residence — Tennessee eviction procedure still applies</p>
  </header>

  <section><h2>1. Parties</h2>
    <p><strong>Operator/Landlord:</strong> {{landlord_name}} ({{landlord_address}})</p>
    <p><strong>Member/Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Nature of This Agreement</h2>
    <p>Tenant is granted the right to occupy <strong>{{unit_or_room_label}}</strong> at <strong>{{property_address}}</strong> and use the shared common areas. Operator may enter with 24 hours' notice (except in emergencies) and may reassign Tenant to a comparable room on 30 days' written notice.</p>
    <p>The "membership" or "room rental" framing applies to house rules and room assignment only. <strong>If Operator seeks to remove Tenant from possession, Operator will follow Tennessee's applicable eviction procedure (Tenn. Code Ann. § 29-18-101 et seq. or URLTA where applicable). Self-help removal is prohibited.</strong> Nothing in this Agreement waives any procedural protection or non-waivable right under Tennessee law.</p>
  </section>

  <section><h2>3. Monthly Fee</h2>
    <p><strong>{{monthly_rent}}</strong> per month, due on the <strong>{{rent_due_day}}</strong>. Utilities included: {{utilities}}. Late fee: <strong>{{late_fee}}</strong> (capped at 10% of the past-due amount per Tenn. Code Ann. § 66-28-201(d) after the 5-day grace).</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
  </section>

  <section><h2>4. Refundable Deposit</h2>
    <p><strong>{{security_deposit}}</strong>, held in compliance with <em>Tenn. Code Ann. § 66-28-301(a)</em> (separate account at a bank or lending institution regulated by the State of Tennessee or any agency of the U.S. government — FDIC-insured banks in any state qualify — with written notice of the institution at signing).</p>
  </section>

  <section><h2>5. Term and Termination</h2>
    <p>From <strong>{{lease_start_date}}</strong> through <strong>{{lease_end_date}}</strong>. Either party may terminate a month-to-month arrangement on 30 days' written notice. Material-breach cure period of 14 days per <em>§ 66-28-505</em>.</p>
  </section>

  <section><h2>6. House Rules</h2>
    <blockquote>{{co_living_rules}}</blockquote>
    <p>Operator may amend on 30 days' notice; amendments shall not unreasonably alter the core benefits.</p>
  </section>

  <section><h2>7. Occupants, Pets, Parking</h2>
    <p>Authorized occupants: {{occupants}}. Pets: {{pets_allowed}}. Parking: {{parking}}.</p>
  </section>

  ${EARLY_TERMINATION_TN}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

const GENERIC_MULTISTATE: SeedTemplate = {
  state: "ALL",
  category: "generic",
  name: "Multi-State Generic Lease",
  description: "Generic residential lease for use in states without a Leasely-curated template. State-specific protections and disclosures may not be reflected — independent attorney review is recommended.",
  variables: [
    "landlord_name", "tenant_name", "tenant_email", "property_address", "property_city",
    "state", "property_zip", "monthly_rent", "security_deposit", "lease_start_date",
    "lease_end_date", "rent_due_day", "late_fee", "utilities", "pets_allowed",
    "parking", "occupants", "payment_methods",
  ],
  citations: ["42 U.S.C. § 4852d"],
  disclosures: ["federal_lead_paint"],
  bodyHtml: `
<article class="lease-document" data-template="generic">
  <header>
    <h1>Residential Lease Agreement</h1>
    <p class="lease-subtitle">For premises located in {{state}}</p>
  </header>

  <section class="legal-disclaimer" style="border-left:4px solid #c00;padding:8px 12px;background:#fff7f7;">
    <p><strong>Generic Template Warning.</strong> This document uses a multi-state generic template because Leasely does not yet maintain a curated template for {{state}}. State-specific protections, required disclosures, late-fee caps, security-deposit caps, and eviction procedures may differ materially from this document. An attorney licensed in {{state}} should review before reliance.</p>
  </section>

  <section><h2>1. Parties</h2>
    <p><strong>Landlord:</strong> {{landlord_name}}<br/><strong>Tenant:</strong> {{tenant_name}} ({{tenant_email}})</p>
  </section>

  <section><h2>2. Property</h2>
    <p>{{property_address}}. Authorized occupants: {{occupants}}.</p>
  </section>

  <section><h2>3. Term</h2>
    <p>From {{lease_start_date}} through {{lease_end_date}}.</p>
  </section>

  <section><h2>4. Rent</h2>
    <p>{{monthly_rent}} per month, due on the {{rent_due_day}} of each month. Late fee: {{late_fee}}.</p>
    <p><strong>Accepted payment methods.</strong> Tenant shall pay rent via any of the following methods accepted by Landlord: <strong>{{payment_methods}}</strong>. Rent is considered paid on the date funds are received and confirmed by Landlord.</p>
  </section>

  <section><h2>5. Security Deposit</h2>
    <p>{{security_deposit}}, held in accordance with the applicable {{state}} law.</p>
  </section>

  <section><h2>6. Utilities, Pets, Parking</h2>
    <p>Utilities included: {{utilities}}. Pets allowed: {{pets_allowed}}. Parking: {{parking}}.</p>
  </section>

  <section><h2>7. Eviction Procedure</h2>
    <p>If Landlord seeks to recover possession of the Property, Landlord shall follow the eviction procedure required by the law of {{state}}. Self-help removal (lockouts, utility shutoffs, removal of property) is prohibited. Nothing in this Lease waives any procedural protection or non-waivable right the Tenant has under applicable law.</p>
  </section>

  ${EARLY_TERMINATION_GENERIC}
  ${FEDERAL_LEAD_PAINT}
  ${COMPLIANCE_BLOCK}
  ${SIGNATURE_BLOCK}
</article>`,
};

export const SEED_TEMPLATES: SeedTemplate[] = [
  NC_RESIDENTIAL, NC_COLIVING, TN_RESIDENTIAL, TN_COLIVING, GENERIC_MULTISTATE,
];
